export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS'
export const GET_WEATHER_LOADING = 'GET_WEATHER_LOADING'
export const GET_WEATHER_FAILED = 'GET_WEATHER_FAILED'

export const GET_LATLON_BY_PLACEID_SUCCESS = 'GET_LATLON_BY_PLACEID_SUCCESS'
export const GET_LATLON_BY_PLACEID_LOADING = 'GET_LATLON_BY_PLACEID_LOADING'
export const GET_LATLON_BY_PLACEID_FAILED = 'GET_LATLON_BY_PLACEID_FAILED'

export const SET_DISPLAYED_LOCATION = 'SET_DISPLAYED_LOCATION'
export const SET_USER_LOCATION = 'SET_USER_LOCATION'
